export type Property = {
  id: string;
  image: string;
  timeAgo: string;
  type: "Apartment" | "House" | "Villa" | "Land";
  price: number;
  size: number; 
  beds: number;
  address: string;
  availableFrom: string;
  city: string;
};

export const cities = [
  "Banjul",
  "Serekunda",
  "Brikama",
  "Bakau",
  "Lamin",
  "Sukuta",
  "Fajara",
  "Brufut",
  "Gunjur",
  "Kotu",
  "Kololi",
  "Yundum",
];

export const properties: Property[] = [
  {
    id: "p001",
    image: "/assets/images/properties/property-1.png",
    timeAgo: "46 secs ago",
    type: "Apartment",
    price: 17950,
    size: 80,
    beds: 2,
    address: "Kotu East, Off Coastal Rd",
    availableFrom: "1 Jan",
    city: "Kotu",
  },
  {
    id: "p002",
    image: "/assets/images/properties/property-2.png",
    timeAgo: "1 min ago",
    type: "House",
    price: 28500,
    size: 150,
    beds: 3,
    address: "Bijilo Highway, Near Turntable",
    availableFrom: "15 Jan",
    city: "Bijilo",
  },
  {
    id: "p003",
    image: "/assets/images/properties/property-3.png",
    timeAgo: "2 min ago",
    type: "Apartment",
    price: 12000,
    size: 65,
    beds: 1,
    address: "Banjul Central, ECOWAS Ave",
    availableFrom: "1 Feb",
    city: "Banjul",
  },
  {
    id: "p004",
    image: "/assets/images/properties/property-4.png",
    timeAgo: "5 min ago",
    type: "House",
    price: 35000,
    size: 200,
    beds: 4,
    address: "Serekunda Pipeline Rd, Off Kairaba Ave",
    availableFrom: "1 Mar",
    city: "Serekunda",
  },
  {
    id: "p005",
    image: "/assets/images/properties/property-5.png",
    timeAgo: "8 min ago",
    type: "Apartment",
    price: 15000,
    size: 70,
    beds: 2,
    address: "Fajara M Section, Atlantic Rd",
    availableFrom: "10 Feb",
    city: "Fajara",
  },
  {
    id: "p006",
    image: "/assets/images/properties/property-6.png",
    timeAgo: "10 min ago",
    type: "Villa",
    price: 55000,
    size: 300,
    beds: 5,
    address: "Brufut Heights, Ocean View",
    availableFrom: "1 Apr",
    city: "Brufut",
  },
  {
    id: "p007",
    image: "/assets/images/properties/property-7.png",
    timeAgo: "12 min ago",
    type: "House",
    price: 22000,
    size: 120,
    beds: 3,
    address: "Brikama Sanchaba, Near Market",
    availableFrom: "20 Jan",
    city: "Brikama",
  },
  {
    id: "p008",
    image: "/assets/images/properties/property-8.png",
    timeAgo: "15 min ago",
    type: "Apartment",
    price: 9000,
    size: 55,
    beds: 1,
    address: "Bakau Freetown, Cape Point",
    availableFrom: "5 Mar",
    city: "Bakau",
  },
  {
    id: "p009",
    image: "/assets/images/properties/property-9.png",
    timeAgo: "18 min ago",
    type: "Land",
    price: 75000, 
    size: 500,
    beds: 0, 
    address: "Lamin Village, Off Brikama Rd",
    availableFrom: "Immediately",
    city: "Lamin",
  },
  {
    id: "p010",
    image: "/assets/images/properties/property-10.png",
    timeAgo: "20 min ago",
    type: "House",
    price: 40000,
    size: 250,
    beds: 4,
    address: "Kololi Senegambia Strip, Tourist Area",
    availableFrom: "1 May",
    city: "Kololi",
  },
  {
    id: "p011",
    image: "/assets/images/properties/property-11.png",
    timeAgo: "22 min ago",
    type: "Apartment",
    price: 18000,
    size: 85,
    beds: 2,
    address: "Serekunda Bundung, Main Rd",
    availableFrom: "15 Mar",
    city: "Serekunda",
  },
  {
    id: "p012",
    image: "/assets/images/properties/property-12.png",
    timeAgo: "25 min ago",
    type: "House",
    price: 25000,
    size: 130,
    beds: 3,
    address: "Sukuta Nema, Behind Schools",
    availableFrom: "1 Apr",
    city: "Sukuta",
  },
  {
    id: "p013",
    image: "/assets/images/properties/property-13.png",
    timeAgo: "28 min ago",
    type: "Apartment",
    price: 10500,
    size: 60,
    beds: 1,
    address: "Banjul Box Bar Rd, Near Port",
    availableFrom: "10 Feb",
    city: "Banjul",
  },
  {
    id: "p014",
    image: "/assets/images/properties/property-14.png",
    timeAgo: "30 min ago",
    type: "Villa",
    price: 60000,
    size: 350,
    beds: 5,
    address: "Fajara Waterfront, Ocean Front",
    availableFrom: "1 Jun",
    city: "Fajara",
  },
  {
    id: "p015",
    image: "/assets/images/properties/property-15.png",
    timeAgo: "32 min ago",
    type: "House",
    price: 30000,
    size: 180,
    beds: 4,
    address: "Gunjur Beach Rd, Fishing Village",
    availableFrom: "1 Mar",
    city: "Gunjur",
  },
  {
    id: "p016",
    image: "/assets/images/properties/property-16.png",
    timeAgo: "35 min ago",
    type: "Apartment",
    price: 14000,
    size: 75,
    beds: 2,
    address: "Bakau Old Town, Near Market",
    availableFrom: "20 Apr",
    city: "Bakau",
  },
  {
    id: "p017",
    image: "/assets/images/properties/property-17.png",
    timeAgo: "38 min ago",
    type: "House",
    price: 27000,
    size: 140,
    beds: 3,
    address: "Brikama Nyambai, Main Highway",
    availableFrom: "1 May",
    city: "Brikama",
  },
  {
    id: "p018",
    image: "/assets/images/properties/property-18.png",
    timeAgo: "40 min ago",
    type: "Apartment",
    price: 9500,
    size: 58,
    beds: 1,
    address: "Serekunda Tallinding, New Rd",
    availableFrom: "10 Jun",
    city: "Serekunda",
  },
  {
    id: "p019",
    image: "/assets/images/properties/property-19.png",
    timeAgo: "42 min ago",
    type: "House",
    price: 32000,
    size: 190,
    beds: 4,
    address: "Lamin Lodge Area, River Front",
    availableFrom: "1 Jul",
    city: "Lamin",
  },
  {
    id: "p020",
    image: "/assets/images/properties/property-20.png",
    timeAgo: "45 min ago",
    type: "Villa",
    price: 70000,
    size: 400,
    beds: 6,
    address: "Kololi Palma Rima, Luxury Estate",
    availableFrom: "1 Aug",
    city: "Kololi",
  },
];